### ISSUE TITLE
It scrolls parent elements inappropriately

### ISSUE THREAD

**Issue by adamreisnz** [KoryNunn/scroll-into-view#28]
I have no fiddle because the HTML is quite complex and I don't have the time to reproduce it in a clean version, but long story short: I'm trying to scroll an element into view in a modal which is positioned absolutely/fixed. What it does, is it scrolls the modal body alright, but it also scrolls the underlying page, which should not happen.

A proposed solution is to allow us to pass in an option to *not* scroll the parent elements. E.g. something like this in the while loop:

```js
while (parent) {
    if (validTarget(parent, parents) && isScrollable(parent)) {
      parents++;
      transitionScrollTo(target, parent, settings, done);
      /* Setting to not scroll parents */
      if (settings.dontScrollParents) {
        return;
      }
    }

    parent = parent.parentElement;

    if (!parent) {
      return;
    }

    if (parent.tagName === 'BODY') {
      parent = window;
    }
  }
```

**Comment by KoryNunn** [comment]
From the readme:

```
validTarget: function(target, parentsScrolled){
        // Only scroll the first two elements that don't have the class "dontScroll"
        return parentsScrolled < 2 && target !== window && !target.matches('.dontScroll');
    }
```

**Comment by adamreisnz** [comment]
Ok, that was slightly hidden in plain sight.

**Comment by lougreenwood** [comment]
It would be handy if the docs explained why this is necessary - it seems that in a default state, the library should scroll only the element supplied as the first argument, but when I add a debugger to `validTarget` I see that the scroll action seems to bubble up the DOM.

Maybe I'm just mis-understanding the library, but it seems that scrolling of parent elements is a niche use-case and probably should be opt-in by default, rather than opt out...?

**Comment by KoryNunn** [comment]
Scrolling parents is the only thing this library was built for. Other libs exist that only scroll the target.

**Comment by lougreenwood** [comment]
👍
