### ISSUE TITLE
Only vertical/horizontal scroll

### ISSUE THREAD

**Issue by Horsetoast** [KoryNunn/scroll-into-view#49]
Thanks for your library, it saved us some time.
Can you also add an option for enabling only vertical or horizontal scroll? 
Or recommend how would I implement this?

**Comment by KoryNunn** [comment]
Hmm, this shouldn't be too hard to add as an option, but it would come with the caveat that the target may not ever scroll into view, since it might be off-screen in a dimention that is locked.

A possibly simple solution is to ensure your scollable elements only scroll in the dimension you want them to, using css: 

```
.scrollElement{
    overflow-x: hidden;
    overflow-y: auto;
}
```

A more dificuly solution would be to calculate the target's offset before scrolling, and use that as a scroll alignment offset:

Setting from the readme:
```
 align:{
        top: 0 to 1, default 0.5 (center)
        left: 0 to 1, default 0.5 (center)
        topOffset: pixels to offset top alignment
        leftOffset: pixels to offset left alignment
    },
```

**Comment by KoryNunn** [comment]
@Horsetoast happy for me to close this?

**Comment by KoryNunn** [comment]
Closing for now, re-open if not resolved by the above suggestions.
