### ISSUE TITLE
Multiple Elements Firing At Same Time Not Working

### ISSUE THREAD

**Issue by alowenthal** [KoryNunn/scroll-into-view#63]
I am trying to fire two separate `scrollIntoView` functions at the same time.  They each work separately but I can't get them to work at the same time.

One is a horizontal overflow-x in its own container.  The other scrolls down the page looking for an element with a particular `id`.

Any suggestions to allow them to work cohesively?

Using like this:

```
// horizontal scroll
const carouselElement = document.querySelector('#carousel-position4');
scrollIntoView(carouselElement);

// vertical scroll down page
const element = document.querySelector('#position4');
scrollIntoView(element, { align: { topOffset: 126 } });
```

**Comment by KoryNunn** [comment]
Hmm, that's an interesting requirement..

Is `#carousel-position4` a child of `#position4`?

If so, why do you need two call? scroll-into-view will recursively allign all scrollable parent elements.

It would be very handy if you could set up an example html page that this scenario fails for, so that I can investigate it.

Thanks.

**Comment by alowenthal** [comment]
I think there must be something else conflicting with this in my React Codebase, because when I extract into Codepen to demo it seems to work as i'd like it to:

https://codepen.io/alowenthal/pen/YMKPBX

Wish me luck!!!

**Comment by KoryNunn** [comment]
¯\_(ツ)_/¯ sorry I cant help.
