### ISSUE TITLE
Feature request: option to fire callback when no scrolling happened

### ISSUE THREAD

**Issue by jpalmieri** [KoryNunn/scroll-into-view#64]
I currently have a feature that toggles a boolean to 'block' `scrollIntoView()` (and some other  functions) from firing multiple times while it's running, and then uses a callback to 'unblock' `scrollIntoView()` and these other functions. However, in some cases, `scrollIntoView()` doesn't scroll (e.g., when `isScrollable()` returns false). This is expected (in my case it's a navbar that only is scrollable in mobile widths), but there's not a clean way to fire my callback in this case, and thus not a clean way to unblock my functions that fire after the callback toggles the boolean.

Sorry if this example is unclear. The main point of it is that I'd like a way to fire a callback in a no-op case. I was thinking an additional `type` might work.

**Comment by jpalmieri** [comment]
PS: my workaround is just to make `isScrollable()` return `true`, so that the callback fires even if it's not scrollable.

**Comment by KoryNunn** [comment]
Hmm, I'm surprised the callback isn't called, I'll investigate.

**Comment by KoryNunn** [comment]
Thanks for that, Bug confirmed, test added, fix added, published as 1.9.6.

**Comment by jpalmieri** [comment]
Awesome. Thanks for the ultra-quick response and fix!

**Comment by psixdev** [comment]
Hi, I have a similar problem in version 1.14.2. When I open the page, I scroll to a certain element (based on url). Before calling scrollIntoView, I delete the scroll event listeners, and restore it inside the callback.

The problem is that sometimes this element may be the topmost, so after calling scrollIntoView the scroll does not occur and callback is not called.

It seems to me that in this case, callback should also be called. Or I should be able to find out that the scroll will not be called, so as not to remove the listeners.

Could you help me?

**Comment by KoryNunn** [comment]
I'm having a hard time understanding the scenario, would you be able to add a failing test?

**Comment by psixdev** [comment]
Sorry, I found an annoying mistake in my code. After fixing it, the problem stopped repeating itself. The library works as I expect
