### ISSUE TITLE
DefinitelyTyped: missing props in Alignment

### ISSUE THREAD

**Issue by Thibaut-Fatus** [KoryNunn/scroll-into-view#67]
The type definition (typescript) were outdated, thus I added 2 props to `Alignment`, you might want to check if this fits you: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35428

**Comment by KoryNunn** [comment]
Thanks, this does not affect me as I don't write typely coupled code :)

I have no knowledge of the typed interfaces on scroll-into-view, but it's probably a good idea to lock interfaces to minor/major versions, since I stick to semver, and a change to minor/major means a change to the interface or functionality.

**Comment by KoryNunn** [comment]
Just checked the comment in that typedef, it says it's for 1.6 where as scroll-into-view is up to 1.9 now.
