### ISSUE TITLE
scroll-into-view does not work in iframe within mobile safari

### ISSUE THREAD

**Issue by andrewwyee** [KoryNunn/scroll-into-view#68]
When scroll-into-view is used within an iframe in mobile safari, it doesn't scroll to the specified element.

I created a jsfiddle that has an iframe with the scroll-into-view [example url](http://korynunn.github.io/scroll-into-view/example/) as the source, but clicking the button doesn't scroll. 

Fiddle link:
https://jsfiddle.net/hLmauk39/1/

**Comment by KoryNunn** [comment]
Thanks for the report. I don't have any apple devices so this is hard for me to address, is this something you might be able to help debug? are there any errors being thrown in the console?

Otherwise I'll try and find someone who does have the hardware to help me out.

**Comment by KoryNunn** [comment]
FYI I put a call out for help: https://twitter.com/KoryNunn/status/1137867277280268289

**Comment by benhoad** [comment]
I'll do some more exploration in the next day or two but preliminary investigation shows it's probably something a bit more rooted in how mobile safari renders iframe contents. So most likely a bug not unique to scroll-into-view...

**Comment by KoryNunn** [comment]
I was able to get some help from @markwylde and it looks like there are quite a few iOS safari iFrame issues, and as such I'll close this issue until a solution looks possible.

I would echo the advice given here: https://github.com/janpaepke/ScrollMagic/issues/800#issuecomment-410203584

iOS + iFrames seem like a combination to be avoided.

**Comment by zanedev** [comment]
Just wanted to add an update in case someone else runs into this.

I ran into the same problem and ended up using a wrapper container around the frame and scrolling that with postMessage instead of using this library for iOS only and it works fine.  

But now iOS 13 appears to have fixed the problem and now this library works in iFrames without any hacks out of the box!

So if you need to support iOS 13+ you should be ok.  If you need to support anything less you'll need to explore other options.

**Comment by KoryNunn** [comment]
@zanedev Awesome, thanks for the info and workaround.
